image: docker:stable
services:
  - docker:dind

stages:  
  - build_test
  - deploy_test   

build_test:
  stage: build_test
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t latest .
    - docker push latest

deploy_test:
  stage: deploy_test
  image: alpine
  environment:
    name: test
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - cp $KUBECONFIG $HOME/.kube/config
    - kubectl get pods
    - curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v2.8.2-linux-amd64.tar.gz
    - tar -zxvf ./helm-v2.8.2-linux-amd64.tar.gz
    - mv ./linux-amd64/helm /usr/local/bin/helm    
    - kubectl apply -f ./cluster/deployment.yaml
  only:
    - master


