image: docker:stable
services:
  - docker:dind

variables:
  PAT: iKS6SmGoxzPgptUBuw3_  

stages:  
  - deploy_test 

deploy_test:
  stage: deploy_test
  image: alpine
  environment:
    name: test
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - echo $KUBERNETES > $HOME/.kube/config
    - echo $HOME/.kube/config
    - export KUBECONFIG=$HOME/.kube/config
    - kubectl get pods
    - curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v2.8.2-linux-amd64.tar.gz
    - tar -zxvf ./helm-v2.8.2-linux-amd64.tar.gz
    - mv ./linux-amd64/helm /usr/local/bin/helm    
    - kubectl apply -f ./cluster/deployment.yaml
  only:
    - master


