- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '/'
- task: Docker@2
  inputs:
    containerRegistry: 'desafiobossa'
    repository: 'desafionode'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'