apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafiobossa  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafiobossa
  template:
    metadata:
      labels:
        app: desafiobossa
    spec:
      containers:
        - name: desafiobossa
          image: registry.gitlab.com/allanrolli/desafiobossa:1.0.0         
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: desafiobossa
spec:
  selector:
    app: desafiobossa
  ports:
    - port: 3000
  type: LoadBalancer