apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafiobossa  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafiobossa
  template:
    metadata:
      labels:
        app: desafiobossa
    spec:
      containers:
        - name: desafiobossa
          image: registry.gitlab.com/allanrolli/desafiobossa:latest         
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: desafiobossa
spec:
  selector:
    app: desafiobossa
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: desafiobossa-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - yasmin.allanteste.cloudns.ph
    secretName: yasmin-tls
  rules:
  - host: yasmin.allanteste.cloudns.ph
    http:
      paths:
      - backend:
          serviceName: desafiobossa
          servicePort: 80